version: "3.9"
services:  
  yolov11:
    image: yolo11:1.0
    container_name: yolov11_ours
    # privileged: true
    # environment:
    #   - DEBUG=1
    #   - SHOW='true'
    #   - DOCKER_BUILDKIT=1
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility,graphics
    volumes:
      - ./:/workspace
      - /home/ecre/myprecious/tao/data/:/data
    # deploy:
    #   mode: replicated
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           count: all 
    #       memory: 16g 
    # shm_size: 16gb
    # runtime: nvidia  # 使用 NVIDIA 容器运行时
    ipc: host        # 设置为 host IPC
    gpus: all 
